### ISSUE TITLE
Boolean Arguments on Request

### ISSUE THREAD

**Issue by Waxter81** [jaxon-php/jaxon-core#61] opened 2019-12-26 23:29 UTC
When I call a Jaxon Request with boolean parameter, PHP function throws an Exception  "Uncaught ArgumentCountError: Too few arguments to function...."

```
<html>
<head></head>
<body>
<form id="formulario">
    <input type="checkbox" ID="myChk" onclick="Ajax.Test.foo4(25,this.checked)">
</form> 
</body>
</html>
```

```
class Test {	
	public function foo4($ID,$isTrue) {				
                $this->response->alert('foo function');
		return $this->response;
	}
}
```

Form Data is sending 2 parameters (Numeric and Boolean):
jxncls: Ajax.Test
jxnmthd: foo4
jxnr: 1577402062576
jxnargs[]: N25
jxnargs[]: Btrue

PHP throws exception:
```
[27-Dec-2019 00:11:20 Europe/Amsterdam] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Ajax\Test::foo4(), 1 passed and exactly 2 expected in C:\x\www\x\jaxon\classes\Test.php:26
Stack trace:
#0 [internal function]: Ajax\Test->foo4(25)
#1 C:\x\www\x\vendor\jaxon-php\jaxon-core\src\Request\Support\CallableObject.php(261): ReflectionMethod->invokeArgs(Object(Ajax\Test), Array)
#2 C:\x\www\x\vendor\jaxon-php\jaxon-core\src\Request\Plugin\CallableClass.php(310): Jaxon\Request\Support\CallableObject->call('foo4', Array)
#3 C:\x\www\x\vendor\jaxon-php\jaxon-core\src\Request\Handler\Handler.php(242): Jaxon\Request\Plugin\CallableClass->processRequest()
#4 C:\x\www\x\vendor\jaxon-php\jaxon-core\src\Request\Handler\Handler.php(305): Jaxon\Request\Handler\Handler->_processRequest()
#5 C:\x\www\x\vendor\jaxon-php\jaxon-core\src\Jaxon.php(398): Jaxon\Request\Handler\Handler->processRequest()
#6 C:\x\www\lapre in C:\x\www\x\jaxon\classes\Test.php on line 26
```

I think the problem is on this method in Request/Handler/Argument class. Boolean values are being ignored and removed from the arguments list:

```
    /**
     * Decode an Jaxon request argument from UTF8
     *
     * @param array             $aDst           An array to store the decoded arguments
     * @param string            $sKey           The key of the argument being decoded
     * @param string|array      $mValue         The value of the argument being decoded
     *
     * @return void
     */
    private function _decode_utf8_argument(array &$aDst, $sKey, $mValue)
    {
        $sDestKey = $sKey;
        // Decode the key
        if(is_string($sDestKey))
        {
            $sDestKey = call_user_func($this->cUtf8Decoder, $sDestKey);
        }

        if(is_array($mValue))
        {
            $aDst[$sDestKey] = [];
            foreach($mValue as $_sKey => &$_mValue)
            {
                $this->_decode_utf8_argument($aDst[$sDestKey], $_sKey, $_mValue);
            }
        }
        elseif(is_string($mValue))
        {
            $aDst[$sDestKey] = call_user_func($this->cUtf8Decoder, $mValue);
        }
        elseif(is_numeric($mValue))
        {
            $aDst[$sDestKey] = $mValue;
        }
    }
```

**Comment by feuzeu** [comment] 2019-12-27 06:45
Hi @Waxter81 
You're right. The issue is fixed in the 3.1.7 release.
Thanks.

**Closed** 2019-12-27 22:39 UTC
