### ISSUE TITLE
$jaxon->callback()->after does not use returned response

### ISSUE THREAD

**Issue by tweb-ix** [jaxon-php/jaxon-core#78] opened 2021-04-14 14:22 UTC
Returned response of after callback is not appended to the current response as described on https://www.jaxon-php.org/docs/v3x/requests/callbacks.html

**Comment by feuzeu** [comment] 2021-04-15 09:30
Hi,
Until the issue is fixed, as a workaround, you can use the global response object returned by `jaxon()->getResponse()` in your callbacks, instead of creating a new response object.
Thierry

**Comment by tweb-ix** [comment] 2021-04-16 09:36
Hi,
thanks for the fast response.
your workaround works for me when changing all registered callbacks (not only after-callback) to the global response object.
Tobias

**Comment by feuzeu** [comment] 2021-04-18 02:23
Fixed in the [3.3.2](https://github.com/jaxon-php/jaxon-core/releases/tag/v3.3.2) release.

**Closed** 2021-05-01 03:16 UTC
